import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import TopNavigation from "./Navigation/TopNavigation";
import SideNavigation from "./Navigation/SideNavigation";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="bg-[#F1F1F1]">
        <div className="flex flex-col h-screen w-screen">
          <TopNavigation />
          <div className="flex flex-1">
            <SideNavigation />
            <div>{children}</div>
          </div>
        </div>
      </body>
    </html>
  );
}
